sudo: false
language: python
python:
  - "2.6"
  - "2.7"
  - "3.4"
script: nosetests
env:
  - DJANGO_VERSION="Django>=1.4,<1.5"
  - DJANGO_VERSION="Django>=1.5,<1.6"
  - DJANGO_VERSION="Django>=1.6,<1.7"
  - DJANGO_VERSION="Django>=1.7,<1.8"
  - DJANGO_VERSION="Django>=1.8,<1.9"
matrix:
  exclude:
     - env: DJANGO_VERSION="Django>=1.7,<1.8"
       python: "2.6"
     - env: DJANGO_VERSION="Django>=1.8,<1.9"
       python: "2.6"
     - env: DJANGO_VERSION="Django>=1.4,<1.5"
       python: "3.4"
install:
  - pip install pep8
  - pip install -q "$DJANGO_VERSION"
  - pip install -r requirements.pip

script: 
  - coverage run demo/runtests.py
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 adminfilters"
after_script:
  - coveralls
